export const ingredients = [
	{
		ingredient_id: 1,
		ingredient_name: "Un",
		group: "Temel Malzemeler",
		type: "Kuru Malzeme",
		price: 5,
		unit: "kg",
		amount: 1000,
	},
	{
		ingredient_id: 2,
		ingredient_name: "Zeytinyağı",
		group: "Yağlar",
		type: "Sıvı Malzeme",
		price: 20,
		unit: "kg",
		amount: 500,
	},
	{
		ingredient_id: 3,
		ingredient_name: "Tavuk Göğsü",
		group: "Et Ürünleri",
		type: "Protein",
		price: 50,
		unit: "kg",
		amount: 1000,
	},
	{
		ingredient_id: 4,
		ingredient_name: "Domates",
		group: "Sebzeler",
		type: "Taze Malzeme",
		price: 10,
		unit: "kg",
		amount: 500,
	},
	{
		ingredient_id: 5,
		ingredient_name: "Pirinç",
		group: "Temel Malzemeler",
		type: "Kuru Malzeme",
		price: 15,
		unit: "kg",
		amount: 1000,
	},
	{
		ingredient_id: 6,
		ingredient_name: "Tuz",
		group: "Baharatlar",
		type: "Kuru Malzeme",
		price: 2,
		unit: "kg",
		amount: 100,
	},
	{
		ingredient_id: 7,
		ingredient_name: "Sarımsak",
		group: "Sebzeler",
		type: "Taze Malzeme",
		price: 8,
		unit: "kg",
		amount: 200,
	},
	{
		ingredient_id: 8,
		ingredient_name: "Soğan",
		group: "Sebzeler",
		type: "Taze Malzeme",
		price: 5,
		unit: "kg",
		amount: 500,
	},
	{
		ingredient_id: 9,
		ingredient_name: "Yeşil Mercimek",
		group: "Baklagiller",
		type: "Kuru Malzeme",
		price: 12,
		unit: "kg",
		amount: 1000,
	},
	{
		ingredient_id: 10,
		ingredient_name: "Tereyağı",
		group: "Yağlar",
		type: "Süt Ürünü",
		price: 25,
		unit: "kg",
		amount: 250,
	},
];
